name: DevSecOps Pipeline

on:
    workflow_dispatch: 
    push: 
        paths-ignore:
        # Can we use '**.md' ?
        - 'README.md'
        - 'SECURITY.md'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - 'app/README.md'
        - 'LICENSE'
        - '.gitignore'
        branches: 
            - development
permissions:
  checks: write
  pull-requests: write
  pages: write
  contents: read
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
    ci-build-pipeline:
        runs-on: ubuntu-20.04
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: JDK 11 Setup
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: 11

            - name: Cache MVN dependencies
              id: mvn-cache
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            
            - name: Build Artifact - Maven
              id: mvn-build
              run: mvn clean package -DskipTests=true
          
            - name: Unit Tests - JUnit and JaCoCo
              id: junit-jacoco
              run: mvn test

            - name: JUnit Report
              uses: dorny/test-reporter@v1
              if: always()
              with:
                name: Maven Tests
                path: target/surefire-reports/*.xml
                reporter: java-junit
                fail-on-error: true

            # - name: Publish Report
            #   uses: turing85/publish-report@v1
            #   if: ${{ always() }}
            #   with:
            #     comment-header: my-comment-header
            #     report-fail-on-error: true # to fail when tests failed
            #     report-name: Tests
            #     report-path: '**/target/surefire-reports/*.xml'
            #     report-reporter: java-junit

            - name: JaCoCo Code Coverage Report
              if: always()
              id: jacoco_reporter
              uses: PavanMudigonda/jacoco-reporter@v4.9
              with:
                coverage_results_path: target/site/jacoco/jacoco.xml
                coverage_report_name: Coverage
                coverage_report_title: JaCoCo
                github_token: ${{ secrets.GITHUB_TOKEN }}
                skip_check_run: false
                minimum_coverage: 40
                fail_below_threshold: true
                publish_only_summary: false

            - name: Add Coverage Job Summary
              run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

            - name: Mutation Testing
              id: pit
              run: |
                mvn org.pitest:pitest-maven:mutationCoverage
            - name: Upload Pitest to Artifacts
              uses: actions/upload-artifact@v2
              with:
                name: pitest-mutation-testing
                path: target/pit-reports/**/* 
   
                  

            
