name: DevSecOps Pipeline

on:
    workflow_dispatch: 
    push: 
        paths-ignore:
        # Can we use '**.md' ?
        - 'README.md'
        - 'SECURITY.md'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - 'app/README.md'
        - 'LICENSE'
        - '.gitignore'
        branches: 
            - development
permissions:
  checks: write
  pull-requests: write
  pages: write
  contents: read
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
    ci-build-pipeline:
        runs-on: ubuntu-20.04
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: JDK 11 Setup
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: 11

            - name: Cache MVN dependencies
              id: mvn-cache
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            
            - name: Build Artifact - Maven
              id: mvn-build
              run: mvn clean package -DskipTests=true
          
            - name: Unit Tests - JUnit and JaCoCo
              id: junit-jacoco
              run: mvn test

            - name: Publish Test Report
              uses: mikepenz/action-junit-report@v4
              if: always()
              with:
                report_paths: 'target/surefire-reports/*.xml'
            
            - name: Generate JaCoCo badge
              id: jacoco
              uses: cicirello/jacoco-badge-generator@v2
              with:
                  badges-directory: badges
                  generate-branches-badge: true
                  generate-summary: true
          
            - name: Log coverage percentages to workflow output
              id: coverage_value
              run: |
                echo "coverage = ${{ steps.jacoco.outputs.coverage }}" 
                echo "branches = ${{ steps.jacoco.outputs.branches }}" 
            # - name: Check coverage %
            #   run: |
            #     if [[ ${{ steps.jacoco.outputs.coverage }}<=0.40 ]];
            #     then
            #       echo "Coverage condition is failed with ${{ steps.jacoco.outputs.coverage }}"
            #       exit 1
            #     fi

            - name: Upload JaCoCo coverage report as a workflow artifact
              uses: actions/upload-artifact@v3
              if: always()
              with:
                name: jacoco-report
                path: target/site/jacoco/

            - name: Mutation Testing
              id: pit
              run: mvn org.pitest:pitest-maven:mutationCoverage
            
            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                # Upload entire repository
                path: '**/target/pit-reports/**/mutations.xml'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v3
              
      
          
            # - run: mkdir staging && cp target/*.jar staging
            # - uses: actions/upload-artifact@v3
            #   with:
            #     name: Package
            #     path: staging
   
                  

            
