name: DevSecOps Pipeline

on:
    workflow_dispatch: 
    push: 
        branches: 
            - development
jobs:
    ci-build-pipeline:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Build Artifact - Maven
              id: mvn-build
              run: mvn clean package -DskipTests=true

            - name: Unit Tests - JUnit and JaCoCo
              id: junit-jacoco
              run: mvn test
            
