name: DevSecOps Pipeline

on:
    workflow_dispatch: 
    push: 
        paths-ignore:
        # Can we use '**.md' ?
        - 'README.md'
        - 'SECURITY.md'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - 'app/README.md'
        - 'LICENSE'
        - '.gitignore'
        branches: 
            - development
jobs:
    ci-build-pipeline:
        runs-on: ubuntu-20.04
        permissions:
          checks: write
          pull-requests: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: JDK 11 Setup
              uses: actions/setup-java@v4
              with:
                distribution: 'zulu'
                java-version: 11

            - name: Cache MVN dependencies
              id: mvn-cache
              uses: actions/cache@v3
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            
            - name: Build Artifact - Maven
              id: mvn-build
              run: mvn clean package -DskipTests=true
          
            - name: Unit Tests - JUnit and JaCoCo
              id: junit-jacoco
              run: mvn test

            - name: Publish Test Report
              uses: mikepenz/action-junit-report@v4
              if: always()
              with:
                report_paths: 'target/surefire-reports/*.xml'
            
            - name: Generate JaCoCo badge
              id: jacoco
              uses: cicirello/jacoco-badge-generator@v2
              with:
                  badges-directory: badges
                  generate-branches-badge: true
                  generate-summary: true
          
            - name: Log coverage percentages to workflow output
              id: coverage_value
              run: |
                echo "coverage = ${{ steps.jacoco.outputs.coverage }}" >> $GITHUB_OUTPUT
                echo "branches = ${{ steps.jacoco.outputs.branches }}" >> $GITHUB_OUTPUT
            - name: Check coverage %
              run: |
                if [[ "${{ steps.coverage_value.outputs.coverage }}"<=40 ]];
                then
                  echo "coverage is leaas than 40%"
                  exit 1
                else
                  echo "Coverage condition is passed with ${{ steps.coverage_value.outputs.coverage }}"
                fi

            - name: Upload JaCoCo coverage report as a workflow artifact
              uses: actions/upload-artifact@v3
              if: always()
              with:
                name: jacoco-report
                path: target/site/jacoco/
          
            - run: mkdir staging && cp target/*.jar staging
            - uses: actions/upload-artifact@v3
              with:
                name: Package
                path: staging
   
                  

            
